spring:
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entities: false
  datasource:
    url: jdbc:postgresql://db:5432/events
    username: cnbrkaydemir
    password: password

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem